# Generated by Django 2.1.3 on 2018-11-20 11:12

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_affiliate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliate_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, unique=True),
        ),
    ]
