# Generated by Django 2.1.3 on 2018-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181120_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
